# Generated by Django 3.2 on 2021-05-01 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('accounts', '0002_opinion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='comment',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
